# Generated by Django 5.1.8 on 2025-04-17 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('order_number', models.IntegerField(verbose_name='Numero de orden')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de orden')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
